### ISSUE TITLE
Coinbase Transactions Aren't Processed

### ISSUE THREAD

**Issue by noahShinabarger** [robertwb/bitcoin-taxes#16]
Coinbase must have changed the format of the .csv they make available; the rows are much different than as specified in the Coinbase parser and the entire parser will need to be updated.

**Comment by hamstercrack** [comment]
I haven't tried the Coinbase one, but I tried the Coinbase Pro one. Make sure to use the "Fills" export, not "Accounts".  You have to remove the first column "portfolio" and then it will work using the GdaxFillsParser. It should be easy to update the code to recognize that first "portfolio" column.

However, I'm not sure the script is working. Perhaps it's only handling transactions on a USD exchange, since it doesn't seem to report anything on a BTC exchange.

**Comment by robertwb** [comment]
I've updated the scripts to also understand the new format for Coinbase Pro. You're right, it only understands (at the moment) the USD-BTC accounts. Note that you need both "fills" and "accounts" to track cost basis of deposits and withdrawals (though fills alone is sufficient if no BTC was deposited/withdrawn).

As for the "vanilla" Coinbase, these have changed dramatically (and not for the better, e.g. there seems to be no information about the wallet or manually entered notes for a transaction). This'll have to be updated.

**Comment by robertwb** [comment]
Coinbase's new format no longer contains all the information needed to track cost basis. I created a new script that uses their API to download this information into a format that the main script can then use.
